### ISSUE TITLE
点歌API无法准确识别歌曲

### ISSUE THREAD

**Issue by seven7a** [jxmm52547/Practical-Widgets#1]
貌似无法准确识别部分游戏出的音乐，部分流行歌暂时没有发现问题
版本：0.4.2.Alpha2
![屏幕截图 2023-05-19 203108](https://github.com/jxmm52547/Practical-Widgets/assets/40330193/91363cff-1dd2-4a65-83c3-bdf4da0af3e7)
![屏幕截图 2023-05-19 203131](https://github.com/jxmm52547/Practical-Widgets/assets/40330193/92723590-d20f-4f2d-a142-56086f27392f)

**Comment by jxmm52547** [comment]
这个我知道，就是看别人做了点歌功能想自己做一个，然后就随便写的，识别不准确的问题我看后面给升级吧

**Comment by jxmm52547** [comment]
已于 `V0.5.2` 版本修复, 改为先发送该歌名的歌曲列表给予选择
