### ISSUE TITLE
公会数据

### ISSUE THREAD

**Issue by MC-luoluo** [jxmm52547/Practical-Widgets#3]
{"guild":{"id":"公会id(简单理解为Hypixel的识别码就行)","name":"公会名字","name_lower":"名字小写","created":"公会创建的unix时间戳","members(成员列表}":[{"uuid":"成员的MCUUID(建议通过MOJANGAPI转为name后显示)","rank":"成员在公会的职位","joined":"加入公会的unix时间戳","questParticipation":"该成员完成的任务(公会->每周公会任务中,该成员为这个任务做出的贡献,只需完成挑战就能增加)","expHistory":"最近7天内该成员为公会获得的经验"}],"ranks":[{"name":"职位名称","default":"默认职位","tag":"该职位的tag,会在公会消息后显示","created":"该职位的创建时间","priority":"职位优先级,会在被提拔时依次提升"}],"description":"公会描述","achievements(公会成就)":{"ONLINE_PLAYERS":"最高同时在线人数","EXPERIENCE_KINGS":"一天时间最高获得的经验","WINNERS":"似乎是胜利过多少次游戏(还不确定)"},"exp":"公会总经验,可以以此计算等级","preferredGames":["公会主打游戏"],"tag":"公会标签,在此公会中的玩家会在玩家列表(Tab)和名字后面显示","tagColor":"公会标签颜色","guildExpByGameType":{"公会通过各种游戏获取的经验":"是个列表,此处以原文显示即可"}}}

**Comment by MCluoluow** [comment]
这个就...放VSC里格式化文档就行(

**Comment by jxmm52547** [comment]
V0.6.0完成
