### ISSUE TITLE
Arcade games数据不完整

### ISSUE THREAD

**Issue by MC-luoluo** [jxmm52547/Practical-Widgets#4]
僵尸末日(zombies)分为3个地图，每个地图都有不同的数据，例如最佳回合数分为["best_round_zombies","best_round_zombies_deadend","best_round_zombies_alienarcadium"]，但目前使用/hyp arc所得到的数据只写了其中一个
![图片](https://github.com/jxmm52547/Practical-Widgets/assets/113677351/20689c7d-a9b5-4590-b102-5bde70f906ac)
![图片](https://github.com/jxmm52547/Practical-Widgets/assets/113677351/47c0643c-fadc-411c-adbb-8db73ef7a95f)
查询的uuid：ef6aa13fd11c4fc5a77f0b6ba7f26b10

**Comment by jxmm52547** [comment]
V0.6.0修复
![image](https://github.com/jxmm52547/Practical-Widgets/assets/84485811/d990db23-0292-4d2a-ae5b-1900b77aaca1)

**Comment by MCluoluow** [comment]
外星游乐园的“星”字打错了
![图片](https://github.com/jxmm52547/Practical-Widgets/assets/113677351/efcd4e7d-6bf5-43ca-87d2-5213e1636cd2)
