### ISSUE TITLE
对公会数据的建议

### ISSUE THREAD

**Issue by MC-luoluo** [jxmm52547/Practical-Widgets#5]
1. 不需要列出所有公会成员，只需要写出 _当前查询成员数据_ 和 _Guild Master的名字_ 即可。
2. 公会方面的数据需要列出：
- 公会名字
- 公会会长
- 公会成员数
- 公会创建时间
- 公会等级
- 经验进度（例如：1.83/3M 61%）
- 公会最高同时在线人数
- 每日最高经验
- 公会胜场数
- 公会最近一周每天获取的经验及总和
- 平均每位公会成员最近一天和一周获取的经验
3. 对于查询成员数据，除了公会基础数据还需要列出查询的成员的以下数据：
- 该成员的公会rank
- 该成员加入公会的时间
- 该成员完成了多少公会任务
- 该成员最近一周每天获取的经及总和
- 该成员最近一周每天获取的经验在该公会排多少名

>例如在EST时间2023年12月31日查询成员LiSi获取的数据：

>公会：GongHui
公会会长：ZhangSan
公会成员数：25
公会创建时间：2023年1月1日13:00
公会等级：112级（1.83/3M经验 61%）
最高同时在线：15
每日最高经验：2.57M
公会胜场数：249
公会每周经验：9.79M
2023/12/31：1.45M
2023/12/30：2.42M
2023/12/29：1.58M
2023/12/28：2.45M
2023/12/27：1.05M
2023/12/26：805.24K
2023/12/25：49.76K
平均每位成员经验：
今日：58040 一周：391.92k
>
>成员：LiSi
公会rank：member
加入时间：2023年5月29日
完成公会任务：568
个人每周经验：900K
2023/12/31：125.87K `#5/25`
2023/12/30：503.84K `#1/25`
2023/12/29：0 `#20/25`
2023/12/28：117.42K `#6/25`
2023/12/27：14039 `#14/25`
2023/12/26：63523 `#9/25`
2023/12/45：78943 `#6/25`

>_注：经验值超过100K时使用K做单位，超过1000K时使用M做单位，精确到两位小数。#x/xx使用`code`的原因是会与issues链接冲突，用于插件中时不需要。_

**Comment by jxmm52547** [comment]
V0.6.0完成
